# Copyright (C) 2017 The LineageOS Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This file is generated by device/samsung/hl3g/setup-makefiles.sh

PRODUCT_COPY_FILES += \
    vendor/samsung/hl3g/proprietary/bin/cbd:system/bin/cbd \
    vendor/samsung/hl3g/proprietary/etc/wifi/bcmdhd_apsta.bin:system/etc/wifi/bcmdhd_apsta.bin \
    vendor/samsung/hl3g/proprietary/etc/wifi/bcmdhd_ibss.bin:system/etc/wifi/bcmdhd_ibss.bin \
    vendor/samsung/hl3g/proprietary/etc/wifi/bcmdhd_mfg.bin:system/etc/wifi/bcmdhd_mfg.bin \
    vendor/samsung/hl3g/proprietary/etc/wifi/bcmdhd_sta.bin:system/etc/wifi/bcmdhd_sta.bin \
    vendor/samsung/hl3g/proprietary/etc/wifi/cred.conf:system/etc/wifi/cred.conf \
    vendor/samsung/hl3g/proprietary/etc/wifi/nvram_mfg.txt:system/etc/wifi/nvram_mfg.txt \
    vendor/samsung/hl3g/proprietary/etc/wifi/nvram_net.txt:system/etc/wifi/nvram_net.txt \
    vendor/samsung/hl3g/proprietary/lib/hw/consumerir.default.so:system/lib/hw/consumerir.default.so \
    vendor/samsung/hl3g/proprietary/lib/libbt-vendor.so:system/lib/libbt-vendor.so \
    vendor/samsung/hl3g/proprietary/lib/libsec-ril.so:system/lib/libsec-ril.so \
    vendor/samsung/hl3g/proprietary/vendor/firmware/bcm4335_V0105.0540.hcd:system/vendor/firmware/bcm4335_V0105.0540.hcd \
    vendor/samsung/hl3g/proprietary/vendor/firmware/bcm4335_V0105.0540_wisol.hcd:system/vendor/firmware/bcm4335_V0105.0540_wisol.hcd \
