#!/system/bin/sh
#
# Print startup info
#

while [ "`getprop sys.boot_completed | tr -d '\r' `" != "1" ] ; do sleep 1; done

am start --user 0 com.incallaudio.fix/io.kodular.eylemseskir.incallaudiofix.Screen1
